### ISSUE TITLE
Game crushes

### ISSUE THREAD

**Issue by lotfijb** [lotfijb/TetrisGame#1]
The game crashes if the user doesn't pick a difficulty level and starts the game
Any help is much appreciated

**Comment by furkangunduz** [comment]
Hey you should begin with default difficulty. Your difficulty has no default value so it is undefined at the start. And you are calcualting the speed with this undefined value and it make crash. I also add 2 line of css to help looks nice. I made pull request for you.  you can check it.

**Comment by lotfijb** [comment]
Thank you so much
